[tool.commitizen]
name = "cz_customize"
version = "0.1.0"
tag_format = "v$version"
update_changelog_on_bump = true
bump_message = "bump: version $current_version → $new_version"
allow_abort = false

# Настройки bump
bump_pattern = "^(feat|fix)"
bump_map = {feat = "MINOR", fix = "PATCH"}

# Настройки changelog 1
changelog_pattern = "^(feat|fix|docs|style|refactor|test|chore)/\\S+ \\| #\\d+ \\|"
change_type_order = ["feat", "fix", "refactor", "docs", "style", "test", "chore"]
change_type_map = {feat = "🚀 Новый функционал", fix = "🐛 Исправления багов", refactor = "♻️ Рефакторинг", docs = "📝 Документация", style = "🎨 Стилизация", test = "✅ Тесты", chore = "🔧 Техническая работа"}

[tool.commitizen.customize]
# Кастомный формат: {Тип задачи}/{название ветки} | #{ID задачи в Аспро} | {Описание}
message_template = "{{task_type}}/{{branch_name}} | #{{aspro_id}} | {{description}}"
example = "feat/user-auth | #12345 | добавлена JWT аутентификация"

# Интерактивные вопросы для всех обязательных полей
[[tool.commitizen.customize.questions]]
type = "list"
name = "task_type"
message = "🎯 Выберите тип задачи:"
choices = [
    {value = "feat", name = "feat - Новый функционал"},
    {value = "fix", name = "fix - Исправление бага"},
    {value = "docs", name = "docs - Документация"},
    {value = "style", name = "style - Стилизация"},
    {value = "refactor", name = "refactor - Рефакторинг кода"},
    {value = "test", name = "test - Тесты"},
    {value = "chore", name = "chore - Техническая задача"}
]

[[tool.commitizen.customize.questions]]
type = "input"
name = "branch_name"
message = "🌿 Введите название ветки:"

[[tool.commitizen.customize.questions]]
type = "input"
name = "aspro_id"
message = "🔢 Введите ID задачи в Аспро (только цифры):"

[[tool.commitizen.customize.questions]]
type = "input"
name = "description"
message = "📝 Введите описание (минимум 3 символа):" 