# Pre-commit hooks для валидации коммитов
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1  # Используйте последнюю версию
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]
        
  # Дополнительные хуки для качества кода
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json 